In [4]:
import cv2
import os
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import time

pygame 2.5.2 (SDL 2.28.3, Python 3.9.17)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [8]:
mixer.init()
sound = mixer.Sound('alarm.wav')

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")
model = load_model('D:\DATASET\Models')


lbl=['Close', 'Open']

path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score = 0

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray,minNeighbors = 3,scaleFactor = 1.1,minSize=(25,25))
    eyes = eye_cascade.detectMultiScale(gray,minNeighbors = 1,scaleFactor = 1.1)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (255,0,0) , 3 )

    for (x,y,w,h) in eyes:

        eye = frame[y:y+h,x:x+w]
        #eye = cv2.cvtColor(eye,cv2.COLOR_BGR2GRAY)
        eye = cv2.resize(eye,(80,80))
        eye = eye/255
        eye = eye.reshape(80,80,3)
        eye = np.expand_dims(eye,axis=0)
        prediction = model.predict(eye)
        print(prediction)
       #Condition for Close
        if prediction[0][0]>0.30:
            cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            score=score+1
            #print("Close Eyes")
            if(score > 20):
                try:
                    sound.play()
                except:  # isplaying = False
                    pass

        #Condition for Open
        elif prediction[0][1] > 0.70:
            score = score - 1
            if (score < 0):
                score = 0
            cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
            #print("Open Eyes")
            cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)

    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[0.4084323  0.59156775]]
[[2.2508322e-04 9.9977487e-01]]
[[0.8773195  0.12268047]]
[[0.4723464  0.52765363]]
[[0.91989297 0.08010704]]
[[0.52333635 0.4766636 ]]
[[0.50711495 0.49288502]]
[[0.86955136 0.13044867]]
[[0.37453213 0.6254679 ]]
[[0.6651549  0.33484513]]
[[0.93155396 0.06844604]]
[[1.1799938e-05 9.9998820e-01]]
[[0.34438154 0.6556184 ]]
[[0.19846502 0.801535  ]]
[[1.2695629e-06 9.9999869e-01]]
[[0.9613311  0.03866887]]
[[0.4477828 0.5522172]]
[[0.2796416 0.7203584]]
[[1.2974869e-04 9.9987018e-01]]
[[0.801235   0.19876496]]
[[0.06350332 0.9364967 ]]
[[0.25476453 0.7452355 ]]
[[9.9952900e-01 4.7100423e-04]]
[[0.5059379  0.49406216]]
[[0.00420724 0.99579275]]
[[0.6312889  0.36871108]]
[[0.24125564 0.75874436]]
[[0.9943082  0.00569183]]
[[0.24332081 0.75667924]]
[[0.62158364 0.37841642]]
[[0.40319985 0.5968002 ]]
[[0.9937402  0.00625981]]
[[0.9848317  0.01516839]]
[[0.250899   0.74910104]]
[[0.94489884 0.05510114]]
[[0.9898101  0.01018994]]
[[2.4705607e-05 9.9997532e-01]]
[[0.48

[[0.8849962  0.11500383]]
[[0.08852476 0.9114752 ]]
[[0.42108768 0.5789123 ]]
[[0.00350234 0.9964977 ]]
[[0.5041482 0.4958518]]
[[1.4890093e-04 9.9985111e-01]]
[[0.26416954 0.7358304 ]]
[[0.22227737 0.7777226 ]]
[[0.4994617 0.5005383]]
[[0.4091238 0.5908762]]
[[0.57645583 0.4235442 ]]
[[0.3148524 0.6851476]]
[[0.23906839 0.7609316 ]]
[[0.51712674 0.48287323]]
[[0.65277    0.34723002]]
[[7.6139334e-04 9.9923861e-01]]
[[0.00603928 0.99396074]]
[[0.9699131  0.03008686]]
[[0.0375815 0.9624185]]
[[0.98095465 0.01904542]]
[[0.92893785 0.07106215]]
[[0.9486107  0.05138926]]
[[0.08257096 0.91742903]]
[[0.04657759 0.9534224 ]]
[[0.8112098  0.18879017]]
[[0.00141155 0.9985884 ]]
[[0.6698567  0.33014324]]
[[0.9239949  0.07600509]]
[[0.9758415  0.02415848]]
[[0.15087432 0.8491257 ]]
[[0.8880237 0.1119763]]
[[0.9357444  0.06425565]]
[[0.857399   0.14260101]]
[[0.8572423  0.14275767]]
[[3.4537169e-04 9.9965465e-01]]
[[0.0037933  0.99620664]]
[[0.40010023 0.5998997 ]]
[[0.97917855 0.02082146]]
[[0.00